/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 DamagedHelmet.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/DamagedHelmet.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['node_damagedHelmet_-6514'].geometry} material={materials.Material_MR} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/DamagedHelmet.gltf')
